server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  cloud:
    compatibility-verifier:
      enabled: false
  application:
    name: ms-vakitas
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
  datasource:
    url: jdbc:mysql://localhost:3306/vakitadb?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

#Inicializacion de data en la bd, toma el script que est√° en resources al iniciar el ms
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceURL:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
    app:
      name: ms-vakitas
      version: 1.0.0
      description: Microservicios Vakitas

spring-doc:
  api-docs:
    path: /swagger-vakitas