version: '3.9'
services:
  rabbitmq-container:
    image: rabbitmq:3.9-management
    container_name: rabbit-container
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 15672
      - 5672
    networks:
      - grupo3
  gateway-container:
    image: mcabate/pi:gateway-v4
    restart: on-failure
    container_name: gateway-container
    ports:
      - "8080:8080"
    expose:
      - '8080'
    depends_on:
      - eureka-server-container
    networks:
      - grupo3
  vakitas-container:
    image: mcabate/pi:vakitas-v2
    restart: on-failure
    container_name: vakitas-container
    ports:
      - "9091:9091"
    expose:
      - '9091'
    depends_on:
      - eureka-server-container
    networks:
      - grupo3
  usuarios-container:
    image: mcabate/pi:usuarios-v3
    restart: on-failure
    container_name: usuarios-container
    ports:
      - "9090:9090"
    expose:
      - '9090'
    depends_on:
      - eureka-server-container
    networks:
      - grupo3
  eureka-server-container:
    image: mcabate/pi:eureka-v1
    container_name: eureka-server-container
    ports:
     - "8761:8761"
    expose:
     - '8761'
    networks:
      - grupo3

networks:
  grupo3:
