server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: ms-payment

  data:
    mongodb:
      database: paymentsdb
      port: 27017
      host: 3.90.249.195
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceURL:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.int}
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

management:
  endpoints:
    web:
      exposure:
        include: info
info:
  env:
    enabled: true
  app:
    name: ms-payment
    version: 1.0.0
    description: Microservicios de Pagos


